<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Create' => 'Crear',
    'Heading' => 'título',
    'Yii Forum' => 'Yii Foro',
    'Created At' => 'Creado el',
    'Permissions' => 'Permisos',
    'Get started with Yii' => 'Comience con Yii',
    'My Yii Application' => 'Mi aplicación Yii',
    'Yii Documentation' => 'Yii Documentación',
    'Yii Extensions' => 'Extensiones Yii',
    'Registrations' => 'Registros',
    'Student ID' => 'Matrícula',
    'Modality' => 'Modalidad',
    'Are you sure you want to delete this item?' => '¿Seguro que quieres borrar este artículo?',
    'Create Subject' => 'Crear Materia',
    'Create Curriculum' => 'Crear Carrera',
    'Delete' => 'Eliminar',
    'Message' => 'Mensaje',
    'Reset' => 'reajustar',
    'Search' => 'Búsqueda',
    'Statuses' => 'Los estados',
    'Update' => 'Actualizar',
    'Update Configuration' => 'Actualizar Configuración',
    'Update Student:' => 'Actualizar Estudiante:',
    'Updated At' => 'Actualizado A',
    'Registration Ord' => 'Registros Ordinarios',
    'Registration Exes' => 'Registros Extraordinarios',
    'Curriculum' => 'Carrera',
    'Curriculums' => 'Carreras',
    'Students' => 'Estudiantes',
    'Subject' => 'Materia',
    'Teacher' => 'Maestro',
    'Subjects' => 'Materias',
    'Configuration' => 'Configuración',
    'Configurations' => 'Configuraciones',
    'Regular Subjects' => 'Cursos Regulares',
    'Create Registration' => 'Crear Registro Ordinario',
    'Create Registration Ex' => 'Crear Registro de Extraordinario',
    'Regular Registration' => 'Registro Ordinario',
    'Ex Registration' => 'Registro Extraordinario',
    'Phone' => 'Teléfono',
    'Name' => 'Nombre',
    'Short Name' => 'Abreviación',
    'Schedule' => 'Horario',
    'Classroom' => 'Salón',
    'First Name' => 'Nombre',
    'Last Name' => 'Apellidos',
    'Save' => 'Guardar',
    'Accept' => 'Aceptar',
    'Users' => 'Usuarios',
    'Username' => 'Usuario',
    'Password' => 'Contraseña',
    'Create Users' => 'Crear Usuarios',
    'Create Student' => 'Crear Estudiante',
    'Import' => 'Importar',
    'Reports' => 'Reportes',
    'Administration' => 'Administración',
    'Importations' => 'Importaciones',
    'Educational Model' => 'Modelo Educativo',
    'Max Subject Regular' => 'Cupo Ordinarios',
    'Max Subject Extraordinary' => 'Cupo Extraordinarios',
    'Date Open' => 'Fecha y Hora de Inicio',
    'Date Close' => 'Fecha y Hora de Cierre',
    'Instructions Before Open' => 'Instrucciones Antes de Inicio',
    'Instructions While Open' => 'Instrucciones Durante',
    'Instructions After Close' => 'Instrucciones Después de Cierre',
    'Confirmation Message' => 'Mensaje de Confirmación',
    'Available' => 'Disponible',
];
?>