<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Get started with Yii' => 'Comience con Yii',
    'Heading' => 'título',
    'My Yii Application' => 'Mi aplicación Yii',
    'Yii Documentation' => 'Yii Documentación',
    'Yii Extensions' => 'Extensiones Yii',
    'Yii Forum' => 'Yii Foro',
    'Are you sure you want to delete this item?' => '¿Seguro que quieres borrar este artículo?',
    'Create' => 'crear',
    'Create {modelClass}' => 'Crear {modelClass}',
    'Created At' => 'Creado el',
    'Delete' => 'Eliminar',
    'Message' => 'Mensaje',
    'Permissions' => 'Permisos',
    'Reset' => 'reajustar',
    'Search' => 'Búsqueda',
    'Statuses' => 'Los estados',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass} :',
    'Updated At' => 'Actualizado A',
    'Registrations' => 'Registros',
    'Curriculum' => 'Carrera',
    'Modality' => 'Modalidad',
    'Students' => 'Estudiantes',
    'Student ID' => 'Matrícula',
    'Subject' => 'Materia',
    'Subjects' => 'Materias',
    'Configuration' => 'Configuración',
    'Configurations' => 'Configuraciones',
    'Teacher' => 'Maestro',
    'Regular Subjects' => 'Cursos Regulares',
    'Regular Registration' => 'Registro Regular',
    'Create Registration' => 'Crear Registro Regular',
    'Create Registration Ex' => 'Crear Registro de Extraordinario',
    'Ex Registration' => 'Registro Extraordinario',
    'Phone' => 'Teléfono',
    'Save' => 'Guardar',
    'Accept' => 'Aceptar',
    'Users' => 'Usuarios',
    'Username' => 'Usuario',
    'Password' => 'Contraseña',
    'Create Users' => 'Crear Usuarios',
    'Reports' => 'Reportes',
    'Administration' => 'Administración',

];
?>